### ISSUE TITLE
On-Map pull down for Selecting Base Maps

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#101]
It would be convenient for the user to switch between the new (wonderful) base maps from the map window without having to open up the legend and turning on and off base maps there.

Maybe a new pull down widget between the current map theme (maptab) pull down and the tool pull down.

The only problem with this is that the current setup enables users to choose multiple base maps.  Is there an engineering solution that can enable users to select more than one choice in a pull down?

**Comment by AmherstGIS** [comment]
I'm wondering how much practical use there is in the ability to turn on multiple basemaps at once. Multiple basemaps can already be fused as part of the GPV configuration. The only compelling use that I can think of is in labeling streets, which in my opinion, is best done via a dynamic layer.
