### ISSUE TITLE
Missing Search Stored Procedure Causes Check Configuration Crash

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#102]
The following error (screen shot) is produced when running checkconfiguration.aspx on a configuration that references a stored procedure in GPV50search.StoredProc, but that stored procedure does not exist.

Other missing stored procedures produce an error.  This one crashes Check Configuration.

![screen shot 2016-09-14 at 2 53 50 pm](https://cloud.githubusercontent.com/assets/6412618/18525677/7c8c0a5e-7a8b-11e6-8a2d-9f5c17e95f4f.png)

**Comment by pgirard** [comment]
Fixed
