### ISSUE TITLE
ZoomLevel url parameter not matching zoom level of the map

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#107]
The ZoomLevel url parameter appears to be different than the resulting zoom level of the map in v5. Here's an example to test:
http://gis.amherstma.gov/gpv5/viewer.aspx?centerlat=42.4153882&centerlon=-72.5262010&zoomlevel=17&keepurl=1

The zoomlevel of 17 in the url results in the map drawing at a zoom level of 21.

**Comment by dbreeding** [comment]
Mike, thanks for reporting your issue.  After closer examination of the zoom levels in your current gpv5 deployment, it seems that GPV is showing duplicate sets of titles for different zoom levels.  Meaning zoom levels 10/11, 12/13, 14/15, and 16/17 both seem to show the same tile set.  I don't have a diagnosis but wanted to document another symptom.

**Comment by pgirard** [comment]
Fixed
