### ISSUE TITLE
Search.SequenceNo as text

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#115]
On display, the GPV is ordering Search.SequenceNo as text.
![screen shot 2017-08-23 at 8 42 59 am](https://user-images.githubusercontent.com/6412618/29616841-b95ca0de-87e0-11e7-8121-4b4a3bc1603e.png)

**Comment by pgirard** [comment]
Tested with HAIG.  Searches are sorted on SequenceNo.  Verified by inspecting code.
