### ISSUE TITLE
FunctionTabs=none leaves an open hamburger

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#116]
Map Only URL should not have empty function panel

![screen shot 2017-08-23 at 9 24 33 am](https://user-images.githubusercontent.com/6412618/29618195-562d41a8-87e5-11e7-8a4a-7b4eda84fad7.png)

**Comment by ClaireBrill** [comment]
+1 for addressing this bug.  A user asked for the ability to load the map with both function and data panels closed.

**Comment by pgirard** [comment]
Fixed.
