### ISSUE TITLE
Default Basemap is not default upon open & multi-tileset basemaps show up twice

### ISSUE THREAD

**Issue by MikeOlkinSwsc** [AppGeo/GPV#121]
Issue with the GPV 5.1 beta:

Basemaps aren’t performing as expected; basemaps that are composed of more than one tileset are showing multiple radio buttons. Also, our Imagery basemap is turned on upon open, even though our basemap (listed at the top) is set as the default basemap. Here’s a screenshot:

![gpv51betabasemapsissue](https://user-images.githubusercontent.com/34135006/38942840-e2db11a6-42fd-11e8-8c18-6484f5586392.jpg)

**Comment by pgirard** [comment]
Fixed.
