### ISSUE TITLE
Cannot Create new markup groups

### ISSUE THREAD

**Issue by MikeOlkinSwsc** [AppGeo/GPV#122]
Cannot create new markup groups in GPV 5.1 beta. Markup tools are working properly when used on existing markup groups.

**Comment by xjin-mansfieldma** [comment]
Second this. Cannot create new markup groups.

**Comment by pgirard** [comment]
Fixed.  In no authentication mode the user must enter a name to enable the New button.  This feature had been broken in a previous edit.
