### ISSUE TITLE
Markup panel resizing

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#123]
Resizing the details pane wacks out the entire panel formatting.
![screen shot 2018-04-20 at 11 58 03 am](https://user-images.githubusercontent.com/6412618/39249433-ac2706aa-486c-11e8-8df0-9ca397bf7aed.png)

**Comment by andrewgbuck** [comment]
Review the TextArea for the description field.  See how that box pushed the panel underneath.

**Comment by pgirard** [comment]
Fixed
