### ISSUE TITLE
Draw Measured Length Icon Obscures Second Point

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#127]
Note from a user: “When using the “DRAW MEASURED LENGTH” tool you can’t see the length sometimes because of the pointing hand. Can you get rid of it and just leave the crosshairs?”

This is true, after the first click the ‘+’ turns into a hand which obscures the measurement value.  This occurs in Chrome and IE.  Is there a work around?

**Comment by pgirard** [comment]
Fixed
