### ISSUE TITLE
Add pan function to select tool?

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#131]
Using the Identify/Pan tool as the default tool, when a feature is selected from the search results (or if there is only one result), the GPV switches to the Select tool - usually without the user noticing. Once the Select tool is activated, there is no ability to Pan the map.

Is it possible to have the pan function available when the select function is active?

**Comment by pgirard** [comment]
This would interfere with the box selection capability.  To allow for panning in select mode we would need to create a separate select by box tool.
