### ISSUE TITLE
Reference to side-arrw.png that is now included in all-icons

### ISSUE THREAD

**Issue by jsmeyers** [AppGeo/GPV#133]
There is a lingering reference to an old icon file that is no longer included: side-arrw.png

It should probably be updated to reference the all-icons file.

It can be seen when closing the left pane for search/maps/markup there is a call to it. It is  extra noticeable in some GPV 5.1 sites that display a custom 404 page as a flash. The quickest resolution was to add a blank file to the images folder but that doesn't fix the CSS.

It is called by the CSS below:

.leftNav_panel .leftLinks ul li.active a
{
background-color:#374c5a;
background-image:url(../Images/side-arrw.png
}

**Comment by pgirard** [comment]
Fixed.
