### ISSUE TITLE
Full Extent button should not clear the Selection

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#161]
Clicking the Full Extent button clears the current selection as well as zooming to the full extent.  This prevents viewing the selection in the context of the whole city using the Full Extent button.

Full Extent should just zoom to the full extent without changing anything else in the map.  The Clear button on the Selection tab can always be used to clear the selection if desired.

**Comment by MikeOlkinSwsc** [comment]
I'm seeing the same issue on our GPV 5.1 instance.
