### ISSUE TITLE
URL parameter 'tool=' always chooses select tool!

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#169]
The URL link below activates the SELECT tool even though the IDENTIFY or  PAN tool is selected.  Same thing happens when I switch the highlighted portion to "tool=pan", or if I leave the tool parameter out all together. If a bogus parameter value (tool=andy) is used, an "Unknown Tool Specified" error message is presented.

http://gisweb.albemarle.org/GPV_51/Viewer.aspx?keepurl=1&application=GISWEBApp&maptab=GISWEBMap&tool=identify&targetlayer=ParcelsStacked&targetids=07800000002200

**Comment by pgirard** [comment]
Cannot reproduce.  The tool parameter is activating the correct tool in development.  Tested with select, identify, pan and drawpoint.
