### ISSUE TITLE
"Print" button on Details Pane opens extra window in Chrome browser

### ISSUE THREAD

**Issue by remerick2008** [AppGeo/GPV#171]
"Print" button on Details Pane opens extra window in Chrome browser. The extra window says "loading" and covers the system print dialog box.

![2019-03-05 12_07_44-county of albemarle - gis-web - map](https://user-images.githubusercontent.com/20355914/53823181-3cf9bc80-3f3f-11e9-9efd-4f11e2e71c31.png)

**Comment by pgirard** [comment]
Now it should temporarily popup only the one window needed for printing.
