### ISSUE TITLE
Details panel not displaying on iPad in portrait

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#172]
GPV 5.1.0 (production)
iOS/Safari 12.2

When I click on a feature to identify in portrait, the Leaflet link and overview map arrow move over to make room for the details pane but the pane does not display.  Select works the same way.

![portrait](https://user-images.githubusercontent.com/5191004/57251300-7a4df980-7017-11e9-9be4-245d8ad44e74.gif)

When I flip from portrait to landscape the panel appears.

![portrait_to_landscape](https://user-images.githubusercontent.com/5191004/57251316-81750780-7017-11e9-9c69-5106ba09a1eb.gif)

In landscape mode things work as expected.

![landscape](https://user-images.githubusercontent.com/5191004/57251330-8c2f9c80-7017-11e9-96f6-65aaab06c744.gif)

When I flip back to portrait, the panel disappears again.

![landscape_to_portrait](https://user-images.githubusercontent.com/5191004/57251351-96519b00-7017-11e9-9c92-23f3bf6b4be8.gif)

**Comment by pgirard** [comment]
Fixed.
