### ISSUE TITLE
Comma separated roles not parsed

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#34]
Using database authentication. Users with multiple roles, such as 'a,b' cannot access applications assigned to one of those roles (e.g. 'a')

**Comment by pgirard** [comment]
This now works.  The column is only 25 characters wide so the multiple role names must be short until the column is made wider in the next schema update.  Note that the roles are passed from the GPVUser table to stored procedures unchanged.  Stored procedure authors will need need to check the potentially multiple roles in this string if necessary.
