### ISSUE TITLE
Search.LayerID case sensitivity

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#37]
The LayerID column of the Search config table must match the case of Layer.LayerID.  A case mismatch causes an error even though the foreign key constraint is satisfied.

**Comment by pgirard** [comment]
Case sensitivity continues to be an issue throughout the GPV.  At one point I had started doing a thorough sweep through the code to ensure all IDs were converted to lowercase, thinking it would only take a few hours.  But it became such a huge undertaking that I didn't have time to follow through so I abandoned the effort.  This eventually needs to be addressed.

**Comment by andrewgbuck** [comment]
I just noticed this is also occurring in the SearchInputField.FieldType column.  Who know 'autoComplete' was not a good thing!  BTW, the behavior with the bad spelling was to display the label, but not the box to enter the search input values.
