### ISSUE TITLE
auto search, auto select, when search result returns a single result

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#44]
From ENC:  Can a feature be auto selected when a feature is searched by ID (and return only one result)?  User desires to type the ID, hit search, and then have the map highlight and pan to the point and the data tab opens without having to double click the tree in the side box.  Is this possible?

**Comment by dbreeding** [comment]
Working in alpha using latest dev deployment

**Comment by pgirard** [comment]
Tested in HAIG: set SearchAutoComplete to yes in GPVSettings, searched on HAIG ID HD00008, GPV automatically zoomed to the one found property.
