### ISSUE TITLE
PDF browser misbehavior

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#49]
So, not sure if other people are experiencing this with their GPVs, but in our environment I recently noticed that in some browser/PDF viewer combinations, when you try to create a Printable Map from the GPV you either get:
1) the PDF showing in the browser and when you go to Save, a dialog comes up asking you to save it as .ASPX file (you could actually overwrite the .ASPX and put in .PDF)
--OR—
2)  I’ve seen configurations where after hitting the Create button, an .ASPX file is saved to your PC and then you essentially can’t get the PDF
--OR—
3) I’ve seen it just work as expected, i.e. you hit Create, a PDF is generated and you simply can save it your PC as a PDF.
 
As of yet, I can’t figure out what the pattern is to try to troubleshoot further, so I’m hoping someone else out there can shed some light on this.
 
I’ve seen the problem with Firefox and Chrome w/ or w/o Adobe or Foxit Reader and I’ve seen if behave normally in IE and Opera.
 
Interestingly, changing line 605 in PdfMap.cs from this:
response.AddHeader("Content-Disposition", inline ? "inline" : "attachment" + "; filename=Map.pdf");
To this:
response.AddHeader("Content-Disposition:", inline ? "inline" + ";filename=Map.pdf" : "attachment" + "; filename=Map.pdf");
 
fixes the #2 issue – it now saves it as Map.pdf.  But this doesn’t fix #1.
 
Changing that same line to:
response.AddHeader("Content-Disposition", "attachment; filename=Map.pdf");
 
seems to solve both #1 and #2, but perhaps this is not a viable solution???
 
Anyway, any help would be appreciated.  Thank you.
 
Damon Pettitt, GISP
GIS Coordinator | Albemarle County, VA
(434) 296-5823 ext. 3231 | dpettitt@albemarle.org | www.albemarle.org/gds

**Comment by pgirard** [comment]
Bug in PdfMap.cs.  Change line 605 to:

response.AddHeader("Content-Disposition", (inline ? "inline" : "attachment") + "; filename=Map.pdf");

**Comment by dbreeding** [comment]
Issue resolved by @pgirard
