### ISSUE TITLE
Too many tools in one pull-down

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#55]
I DON’T LIKE:

> having all the tools in one dropdown box.  Having the markup tools in one dropdown is fine, but I most often use the Pan, ID, and Selection tools, so it would be nice to see all three without the dropdown, even though I realize that would make the map slightly less clean.  

From Stephanie Weyer at KZLA

**Comment by dbreeding** [comment]
By now supporting of tablets and mobile devices, GPV screen real estate is at a premium. Storing all GPV tools in one drop-down a straight forward way to save screen space and store the many GPV tools in one place.
