### ISSUE TITLE
Selection behavior issues re: multiple selections

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#56]
I DON’T LIKE:
> how the select features dropdown tool works.  It does less than the ID tool currently since it has no hover function.  “Select features” (plural) makes me think I can click and drag a box with the select features tool and then see the basic info for what I’ve selected under “selection” in the menu box.  Instead I can only click one tree at a time.  If I want more detailed data on one tree, I’ll naturally just click one tree or use the ID tool, but it would be nice to have the option for selecting multiple trees and just seeing the basic info on the left.

From Stephanie Weyer at KZLA/ENC

**Comment by AmherstGIS** [comment]
I agree strongly with this one.  As a consolation, holding down the shift key allows for selection of more than one feature, but it still doesn't allow a box to be drawn around an area to select more than one feature in one action; one click = one feature selected.

**Comment by andrewgbuck** [comment]
Additional comments on the selection tool behavior.  This is from Joe Donovan in Lowell:

"the selection tool is clunky and does not seem to register if you go right to the map by passing any parcel search criteria, if you go to select features and make sure the parcels are selected the tool does not seem to work and intermittently does not work after a parcel search either."

**Comment by andrewgbuck** [comment]
closed by mistake

**Comment by andrewgbuck** [comment]
Additional comments from Lowell:

Could you include installing a selection draw box to the list, our users are accustomed to drawing a box around features to select,

**Comment by dbreeding** [comment]
The multiple feature selection issues has been resolved.  The select features tool in the latest development release allows for a click and drag action to selection of multiple features via a selection rectangle.  A shift+click and drag allows additional features to be added to an already selected set of features.
