### ISSUE TITLE
Mobile Form Factor: UI hard to use

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#57]
I have a Samsung Galaxy S5, so maybe it works differently than an iPhone, but I’m finding the interface hard to use for mobile.  Frankly, it doesn’t feel like it’s made for mobile.

I still like the updated look but have to do so much scrolling around to see both the menu box and details that I get lost, or the screen jams.  If I just want to use the Selection tool in the menu box, I can’t even see the whole box at one time.  And I’ve got serious issues with the boxes in which I’m supposed to type.  See the next section for that.

I understand the complication of making an interface that formats on mobile without it being an entirely separate application, but if there’s a way to at least get the search box to all fit within the screen, that would be nice.

From Stephanie Weyer at KZLA/ENC

**Comment by AmherstGIS** [comment]
Needs more responsive styling.  If initial panel state is influenced by the window width, that would be a good start.

**Comment by AmherstGIS** [comment]
It appears that responsive styling has been added, with the left panels being hidden if the width is too small.  Would be nice to still have the hamburger icon available in order to at least provide the option to use the left panel.

**Comment by dbreeding** [comment]
The responsive styling added provides the functionality that was previously available in the separate mobile version.  Providing left panel functions at this time is outside of the development scope currently.
