### ISSUE TITLE
Email on share panel: not intuitive

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#58]
I can’t tell that the Email option under “Share” is really working, as I just tried emailing myself and it’s not coming up, 

From Stephanie Weyer at KZLA/ENC

[Is the "not coming up" related to an email client is not configured on the browser? - agb]

**Comment by AmherstGIS** [comment]
On that note, I don't think that the Share panel should necessarily be a panel/functiontab. Why not have in icon floating somewhere along the top? The iOS share icon has become recognizable enough that something similar should work quite well.
![share](https://cloud.githubusercontent.com/assets/5639590/10227296/7b76f188-683a-11e5-9f08-020f6ebb21fe.PNG)

On the topic of the email function, the current active functionab is part of the saved configuration that is emailed, so in this new interface, how does that work?  Is it the last active functiontab?  This wouldn't be an issue if Share were not a functiontab.

Should Export be part of Share? I would love to see it floating along the bottom of the interface.  Would "External Map" be a more appropriate name for Export?

**Comment by WalthamGIS** [comment]
Has there been any resolution to this issue? The Email option does not appear to be working at the release of the production version.

**Comment by dbreeding** [comment]
The email option in the current production version is working, but requires the user's to define their  preferred email client (outlook, gmail, etc..) so the mailto: link being created by the GPV can be properly handled.

The email feature was one that was discussed during the GPV user group meeting which we are working to improve.  In the January release, the email feature will directly provide the saved state link that users can then copy and paste into their email message.  This will avoid the email client setup issue currently blocking users from generating their GPV current state link.

**Comment by WalthamGIS** [comment]
Thanks David. Where does that functionality get defined?

**Comment by dbreeding** [comment]
You can defined your default email client at both the browser and system level.  I recommend setting the default email client at the system level so any program requiring some email functionality will know the user's preference.

Unsure of your current browser or system, I can't point your at the correct resource, but a quick search on "Set default email client windows"  or Set default email client mac" will return instructions.

If you use more than one email client frequently, then setting this email client preference at the browser level might make more sense.

**Comment by pgirard** [comment]
Changed to an Email Link option in 4.2.1.  The display of this link should be changed to a non-editable text box that automatically selects the entire string when you click in the box.
