### ISSUE TITLE
Search reset did not reset pull-down to default setting (blank)

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#60]
> The “Reset” didn’t reset my dropdown box selections back to blank, though it did clear the basic data and deleted all the search text. 

From Stephanie Weyer at KZLA/ENC

**Comment by AmherstGIS** [comment]
I'm seeing the same issue on Microsoft Edge & Mac Safari.  Dropdown box selection remains, but doesn't work if hitting Search again, unless selected again from the dropdown list.

**Comment by dbreeding** [comment]
Reset search properly clears dropdown selection in IE11 and Chrome.

**Comment by TComer-AG** [comment]
This was resolved in commit 7b7e23c8d49328e5bf505aa6b5cbd4e857c9000f
