### ISSUE TITLE
Markup tools should be on the markup panel

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#61]
MARKUP:
It’s confusing to have the markup tools hidden in the dropdown within the map screen.  The dropdown should really be within the Markup box in the menu.

From Stephanie Weyer at KZLA/ENC

**Comment by dbreeding** [comment]
GPV tools in the latest version are being stored in a single drop-down list located on the map panel.  Revised help documentation will hopefully reduce / remove any confusion about the location and use of markup tools.

**Comment by andrewgbuck** [comment]
I still think the markup tools should be on the markup panel.  This would actually clean up the main tool menu by removing tools that are only used a small percentage of the time.
