### ISSUE TITLE
No Zoom Tool?

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#63]
In understand that the new interface is designed for compatibility with touch devices, but it sure would be nice to have a good old magnifying glass zoom tool.  Scroll/spread often doesn't approach the economy of zooming to a specific rectangle.

**Comment by andrewgbuck** [comment]
More zoom comments.  This from Joe Donovan in Lowell:

"Also would it be possible to install a map zoom box with the zoom in/out tools, the Shift+Click/Drag functionality works great but I have doubts users here will be savvy with this method."

**Comment by pgirard** [comment]
Box zoom remains available by holding the shift key and dragging a box.  This is functionality built into Leaflet.  We expect the majority of users will use the mouse scroll wheel, zoom buttons, or two-finger touch zoom.

**Comment by seansweeney** [comment]
Just for the record, we've had several requests to get the zoom tool back also.  Our users seem to prefer box zoom, and only our GIS users get/remember the shift-click.
