### ISSUE TITLE
Map doesn't draw when using TargetIds, ActiveMapId & SelectionIds together

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#64]
Please test this link:
http://gis.amherstma.gov/gpv2015/Viewer.aspx?application=parcelapp&keepurl=y&targetids=17d-5&activemapid=17D-5&selectionids=17d-5&tool=select

**Comment by pgirard** [comment]
The combination of targetids and selectionids in a GPV URL is invalid.  You can only use one or the other but not both.  The GPV will now show an error message when both are provided.
