### ISSUE TITLE
MobileViewer in 4.2 Beta

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#65]
Is MobileViewer still a separate app in 4.2 or is Viewer meant to be one app for desktop and mobile?

If the latter then MobileViewer code should be removed from the final distro to eliminate confusion.

If the former then it's not working.  All I get is the screen shown below and the console errors shown below that.

The Zip file has jquery-2.1.4.min.js (as opposed to 1.7.2) and does not have jquery.geo-test.min.js.  Both are referenced in MobileViewer.aspx.

![gpvmobile1](https://cloud.githubusercontent.com/assets/5191004/10283887/aca320b6-6b4f-11e5-84f5-fbb2ed3b4a02.jpg)

![gpvmobile2](https://cloud.githubusercontent.com/assets/5191004/10283891/b09a27b4-6b4f-11e5-955e-c4d2aed3bfd5.png)

**Comment by dbreeding** [comment]
Mobile device access no longer provided using a separate application.  The GPV is now responsive to mobile devices.
