### ISSUE TITLE
Identify in 4.2 beta doesn't work on my phone

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#66]
When I do an identify on my phone with the 4.2 beta Viewer.aspx, the Details pane does not slide out from the right automatically like on the desktop and the overflow menu (3 orange dots on the upper right next to the help button) do nothing when pressed.  On the desktop the overflow button toggles the visibility of the Details pane.

I'm running Chrome 45 on a Motorola Nexus 6 with Android 5.1.1.

**Comment by dbreeding** [comment]
Details panel slides out when using Identify and three dot icon now opens and collapses the details panel in the latest development release.  Testing done: Chrome 46, Samsung S5, Android 5.0.0.

**Comment by seansweeney** [comment]
This is working for me now - thanks.
