### ISSUE TITLE
Map frame altered by clicking and dragging on gray space on mobile

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#69]
In the latest development version of 4.2 (pulled today) on mobile devices.

If I click on the small gray bar across the bottom of the screen and drag up, I lose the bottom half of the map and all the tools and dropdowns.  If I click on the small gray area on the top of the screen and scroll left, I lose most of the tools.  I can recover both by reversing the click-and-scroll, but I think this will be confusing for users.  I discovered it by overshooting when doing a pan.

Tested on:
* Chrome 46 on a Motorola Nexus 6 with Android 6.
* Chrome 46 on a Galaxy S4 with Android 5.0.1.

![Click-and-drag](https://cloud.githubusercontent.com/assets/5191004/11125566/bcefee20-8938-11e5-8f77-68910c8b90ff.png)

![After clicking bottom and dragging up](https://cloud.githubusercontent.com/assets/5191004/11125555/b0ad7466-8938-11e5-84d3-29164dcfbbbd.png)

![After clicking top and dragging left](https://cloud.githubusercontent.com/assets/5191004/11125557/b55c77dc-8938-11e5-8981-1fe64a104103.png)

**Comment by pgirard** [comment]
There was a CSS min-width set on the map, a leftover from the previous version, that was forcing the width of the UI to be larger than the device.  Now fixed.

**Comment by seansweeney** [comment]
Verified fixed for me on the latest version.
