### ISSUE TITLE
Zoom to Selection does not get close enough

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#70]
Zoom to Selection results in a zoom level that is not very close to the selection set.

**Comment by pgirard** [comment]
Leaflet only allows discrete, power-of-two zoom levels.  When told to zoom to an extent (with either marquee zoom or a selected set) Leaflet will zoom to the next highest zoom level which fully contains that extent.  Thus it's possible that a zoom-to-selection might be zoomed out nearly a whole zoom level from the features.  There's really nothing that can be done about this short of rewriting Leaflet's zooming code (and such code would not work with tiles).

Please close this issue if you feel this explanation is sufficient.

**Comment by ClaireBrill** [comment]
In many examples I've looked at, it seems that it is zooming to 2 levels higher, not the next highest zoom level which fully contains the extent.

**Comment by pgirard** [comment]
Tested extensively with HAIG properties.  In all cases the zoom was set to the highest level that showed the selected set of target features in their entirety.
