### ISSUE TITLE
Can't open Style Guide Graphical Representation of GPV UI

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#73]
When I click on the [Style Guide Graphical Representation of GPV UI](https://docs.google.com/a/appgeo.com/presentation/d/166FxdXI8naY592RZiofBWSG8vF_LUb73E3TRkgxaleY/pub?start=false&loop=false&delayms=3000) link on the [Customizing the GPV Interface](https://github.com/AppGeo/GPV/wiki/Customizing-the-GPV-Interface) Wiki page, Google asks for a login to view the document.  When I log in with my Google account, I get the following error:

![image](https://cloud.githubusercontent.com/assets/5191004/11241768/837ab552-8dcb-11e5-9133-169f504e68fc.png)

**Comment by dbreeding** [comment]
replaced shared google doc with PDF
