### ISSUE TITLE
Measured Markup text does not display

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#79]
Measured markup text is not displaying in 4.2.  Measured markups created in 4.2 do display properly in 4.1.  Here are test links to compare:

[http://gis.amherstma.gov/public/Viewer.aspx?state=576309597826] (http://gis.amherstma.gov/public/Viewer.aspx?state=576309597826) - 4.1
[http://gis.amherstma.gov/gpv2015/Viewer.aspx?state=576309597826] (http://gis.amherstma.gov/gpv2015/Viewer.aspx?state=576309597826) - 4.2

**Comment by AmherstGIS** [comment]
Appears to remain an issue in 4.2.1 Production.  However, measured markups DO work in non-saved markups.  Measured markups of all kinds do not work in Mac Safari.

**Comment by pgirard** [comment]
Please verify whether this is still an issue using the latest development code.

**Comment by AmherstGIS** [comment]
No longer an issue, other than the degree symbol not displaying properly.

**Comment by pgirard** [comment]
The degress symbols will be addressed in issue #82.
