### ISSUE TITLE
Gray Selection Boxes Persist in Safari

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#81]
In the Mac Safari browser, selecting multiple features by clicking/dragging does not perform properly.  Only the last feature touched is selected & a gray box remains, persisting throughout the rest of the session.  Here's an example in which I was able to create several gray boxes that persist, even after panning/zooming, clearing the selection, etc:
![grayboxes](https://cloud.githubusercontent.com/assets/5639590/11788581/d7de4548-a25f-11e5-856c-067cccf38b74.png)

**Comment by dbreeding** [comment]
What version of iOS is running on the Mac that is presenting this issue?

**Comment by AmherstGIS** [comment]
OSX El Capitan 10.11.1

**Comment by AmherstGIS** [comment]
Also seeing this on OSX Yosemite 10.10.5

**Comment by AmherstGIS** [comment]
This issue remains in 4.2.1 Production.

**Comment by TComer-AG** [comment]
This issue was affecting all drag events, both shift and drag select and circle markup. It has now been resolved. https://github.com/AppGeo/GPV/commit/4f3888ea477e842b79273709bd17f20472ec9c6e#diff-fa0aa858723e2064ed04d2422589c428
