### ISSUE TITLE
Markup not performing properly

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#82]
I'm seeing very poor performance with markup & cannot determine the cause. Some markup groups display, while others do not at all.  Please compare in http://www.amherstma.gov/newmap vs http://gis.amherstma.gov/public/viewer.aspx?application=parcelapp&activefunctiontab=markup&keepurl=y

Markup groups to try:
"Test" by Mike, 12/17/15
"Test 2" by Mike, 12/22/15
"Thompson Family Plots" by Tuckerj, 12/2/15 -- this one works in both

**Comment by AmherstGIS** [comment]
This issue remains in 4.2.1 Production.

**Comment by pgirard** [comment]
I compared these and many others and they all look fine except that the degree symbol isn't drawing in 4.2.1.  Am I missing something?

**Comment by AmherstGIS** [comment]
Yesterday's fix appears to have cleared up this issue.

**Comment by pgirard** [comment]
Leaving active to address the issue of the degree symbol drawing incorrectly.

**Comment by pgirard** [comment]
The degree symbol does show properly on my machine.  It is showing as a question mark at Amherst.  That part of the markup drawing code has not really changed.  Is this a font issue at Amherst?  The font is Verdana and the character is Unicode 00B0 - Degree Sign.  This can be checked in Windows Character Map program.

**Comment by AmherstGIS** [comment]
I checked the web server & Verdana is installed.  However, I wasn't able to check to see the degree sign specifically.

**Comment by pgirard** [comment]
The degree sign as a question mark, which is what this issue has boiled down to, only appears to be a problem for Amherst.  We will continue to work on this, but I'm tagging it for Milestone 5.0 so that we can release the version 4.2.2 bug fixes.

**Comment by TComer-AG** [comment]
When I go to you site the degree symbol is appearing correctly. See attached.
<img width="1431" alt="screen shot 2016-01-21 at 9 47 38 am" src="https://cloud.githubusercontent.com/assets/6595247/12483645/3acf9774-c024-11e5-9d0e-7665639763c3.png">
