### ISSUE TITLE
Share Panel Display Issues

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#83]
When switching between share panel options, the display of the previous option remains visible.  Also, the email link now generates only text of the hyperlink, without generating an email...is this how it is intended? If so, we should consider a different name for this function.
![sharepaneldisplay](https://cloud.githubusercontent.com/assets/5639590/12235966/32cb25ac-b845-11e5-8d3e-701f3d468b6e.png)

**Comment by dbreeding** [comment]
We can see and will correct the persistence of the map extent information.  You are correct, the email link feature now just provides a link to email.  Many user's struggled to properly define their preferred email client in the past making the original email function non-responsive.

**Comment by AmherstGIS** [comment]
David - Would you check our instance to see whether it is functioning properly? The email isn't a link; it's just text & in order to make use of it, the user needs to manually copy & paste the url.  Is this the way that it is intended?

**Comment by dbreeding** [comment]
Sorry for the confusion.  Your understanding is correct. The "email link" feature is designed to provide a text URL that users can then copy and paste into a email.

**Comment by pgirard** [comment]
See issue #58.  We will make this easier to use in the next update.

**Comment by pgirard** [comment]
Fixed.
