### ISSUE TITLE
Inset Map is hidden by the Details panel

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#91]
The inset map hides behind the details panel, until the details panel is turned off, then back on.

**Comment by dbreeding** [comment]
Please provide browser version, type, and device details.  We can't currently reproduce the details panel rolling over the inset map using http://gis.amherstma.gov/public/Viewer.aspx

**Comment by AmherstGIS** [comment]
I can't reproduce this issue now, either. Feel free to close this.
