### ISSUE TITLE
Zero-length measured length markup disables map refresh

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#92]
Double-clicking to begin a measured length markup creates a zero-length line. The map will not refresh if one of these has been created. If the zero length line is deleted, the map will function properly again. 

Very interesting bug. This issue does not appear to exist with any other type of markup. This has been tested & confirmed in Mac Safari, Chrome & Windows IE.

**Comment by pgirard** [comment]
Fixed
