### ISSUE TITLE
Zoom to larger scale(s)

### ISSUE THREAD

**Issue by seansweeney** [AppGeo/GPV#93]
We've had several requests from our mobile users in the field (especially DPW) to be able to zoom in to larger scales.  The new zoom limit in 4.2 makes it hard to distinguish features in busy intersections.  I know that Leaflet supports fractional zoom (since 1.0-beta1), but I don't know how much this would degrade the map.

**Comment by seansweeney** [comment]
More info: It looks like I’ve always had my ZoomLevels (in Web.Config) set to 17, but this number appears to give me a different max zoom in 4.1 and 4.2.  I tried changing it to 19 in 4.2 and that did not seem to make any difference.  Below are screenshots showing the difference between 4.1 and 4.2 max zoom (respectively) on the desktop.

![gpv_max_zoom_4 1](https://cloud.githubusercontent.com/assets/5191004/15782840/be40cf88-2979-11e6-921e-9579c989a847.png)
![gpv_max_zoom_4 2](https://cloud.githubusercontent.com/assets/5191004/15782857/cf7531c2-2979-11e6-9f3d-5b0a5396453a.png)

**Comment by pgirard** [comment]
Fixed in version 5.0.
