### ISSUE TITLE
Shift in Selection Geometry

### ISSUE THREAD

**Issue by AmherstGIS** [AppGeo/GPV#97]
GPV 5 selected features are shifted, much like the transformation has not been set:
![shift](https://cloud.githubusercontent.com/assets/5639590/16522753/9e7395f0-3f6d-11e6-8d5d-cc541a19a2ae.png)

The map service displayed in the above image is using data that is in Stateplane MA Mainland NAD83 Feet, but the service is in web Mercator, with the transformation set properly.

**Comment by AmherstGIS** [comment]
I just updated to the current release of 5.0 and this issue is still present. Selection geometry consistently misaligns to the south.

**Comment by AmherstGIS** [comment]
This issue is still present. Is anyone else seeing this on other GPV5 instances?

**Comment by xjin-mansfieldma** [comment]
Second this. I am having the same issue with 5.0. Parcel in the dynamic service is shifted about 3 ft to the south compared to parcel in the tiled service. 

![image](https://cloud.githubusercontent.com/assets/24320723/21821939/5958d20a-d743-11e6-92d3-a381d31d6f6c.png)

**Comment by pgirard** [comment]
Addressed by the addition of optional shift settings in GPVSetting.
