### ISSUE TITLE
Authentication Time Out Workflow

### ISSUE THREAD

**Issue by andrewgbuck** [AppGeo/GPV#98]
The GPV authentication appears to be timing out when AGS recycles over night.  I have only seen the behavior when I try to refresh data tabs, but it may show up elsewhere.
1. Leave your browser open overnight; access a different maptab; experience the authentication challenge within the datatab panel:

![screen shot 2016-07-14 at 9 29 44 am](https://cloud.githubusercontent.com/assets/6412618/16848401/a991dad6-49c3-11e6-9ce4-15fe3719a7d7.png)
1. Enter a valid username and password; hit enter; experience an internal error (curiously its about the selection panel):

![screen shot 2016-07-14 at 9 30 34 am](https://cloud.githubusercontent.com/assets/6412618/16848428/cd6c50ee-49c3-11e6-96b7-fb9beaa01fd9.png)
1. Hit the refresh button; proceed on your way; ask yourself, "Is this a feature?"

![screen shot 2016-07-14 at 9 31 09 am](https://cloud.githubusercontent.com/assets/6412618/16848513/1c83fba0-49c4-11e6-84c4-65fb06b31d78.png)

**Comment by andrewgbuck** [comment]
In 1. above, my workflow should read access a different DATAtab.

**Comment by pgirard** [comment]
When authentication is required the client now checks with the server every 30 seconds to see if the user if still logged in.  If not, the GPV reverts to the login screen.
